### ISSUE TITLE
UndefVarError: @colorant_str not defined

### ISSUE THREAD

**Issue by etorkia** [GiovineItalia/Gadfly.jl#1368]
I have a series of charting functions built using Gadfly... Suddenly I am having an issue with the Scale.color_discrete_manual function that is returning : UndefVarError: @colorant_str not defined. 

There is also an issue with the recognition of **colorant"deep sky blue"** as an available color. This error is preventing the entire package from precompiling. 

Here is the offending plot:
```julia
plot(graph_tbl, y=:name, x=:correlation, Guide.Title("Variables with Biggest Impact"),
Guide.xlabel("Rank Correlation"), Guide.ylabel("Input"), Geom.bar(orientation=:horizontal),
Theme(bar_spacing=10pt), color=:impact,
Scale.color_discrete_manual(colorant"red", colorant"deep sky blue"),
Scale.x_continuous(minvalue=-1, maxvalue=1))
```
Here is the stack trace:

```
ERROR: LoadError: LoadError: LoadError: UndefVarError: @colorant_str not defined
Stacktrace:
 [1] top-level scope
 [2] #macroexpand#32 at .\expr.jl:107 [inlined]
 [3] macroexpand at .\expr.jl:106 [inlined]
 [4] docm(::LineNumberNode, ::Module, ::Any, ::Any, ::Bool) at .\docs\Docs.jl:509 (repeats 2 times)
 [5] @doc(::LineNumberNode, ::Module, ::String, ::Vararg{Any,N} where N) at .\boot.jl:461
```

Any help would be great!

**Comment by bjarthur** [comment]
possibly related to [Colors 0.10 failing](https://github.com/GiovineItalia/Gadfly.jl/pull/1367) and [Colors 0.11 working](https://github.com/GiovineItalia/Gadfly.jl/pull/1369).  see this [Colors.jl issue](https://github.com/JuliaGraphics/Colors.jl/pull/383).

**Comment by kimikage** [comment]
I'm sorry but I *breaked* the color parser (https://github.com/JuliaGraphics/Colors.jl/pull/360)
"deep sky blue" is invalid on Colors.jl v0.10 and *v0.11*. Should I fix this problem by reverting?

**Comment by Mattriks** [comment]
x11 color names are user-friendly, I think that most users are not e.g. RGBA aficionados.

**Comment by kimikage** [comment]
I agree with you.
However, I think the use of original X11 color names (i.e. [rgb.txt](https://gitlab.freedesktop.org/xorg/app/rgb/raw/master/rgb.txt)) causes some confusion.
[NamedColors.jl](https://github.com/JuliaGraphics/NamedColors.jl) supports the X11 color names.

**Comment by etorkia** [comment]
Thanks for the quick turn-around. Should I change the dependencies for Colors to 0.1 or has the issue been fixed and I need to resolve Gadfly again?

I installed Gadfly 1.0.1 and Colors 0.11...

Here is the stack trace:

```
 Info: Precompiling MCHammer [58716550-704d-11e9-05c2-8f708e47025f]
ERROR: LoadError: LoadError: LoadError: LoadError: Unknown color: deep sky blue
Stacktrace:
 [1] error(::String, ::String) at .\error.jl:42
 [2] _parse_colorant(::String) at C:\Users\enrique.TPNETWORKS\.julia\packages\Colors\7Wrap\src\parse.jl:125
 [3] _parse_colorant at C:\Users\enrique.TPNETWORKS\.julia\packages\Colors\7Wrap\src\parse.jl:129 [inlined]
 [4] parse(::Type{ColorTypes.Colorant}, ::String) at C:\Users\enrique.TPNETWORKS\.julia\packages\Colors\7Wrap\src\parse.jl:163
 [5] @colorant_str(::LineNumberNode, ::Module, ::Any) at C:\Users\enrique.TPNETWORKS\.julia\packages\Colors\7Wrap\src\parse.jl:174
 [6] #macroexpand#32 at .\expr.jl:107 [inlined]
 [7] macroexpand at .\expr.jl:106 [inlined]
 [8] docm(::LineNumberNode, ::Module, ::Any, ::Any, ::Bool) at .\docs\Docs.jl:509 (repeats 2 times)
 [9] (::DocStringExtensions.var"#20#21"{typeof(DocStringExtensions.template_hook)})(::LineNumberNode, ::Vararg{Any,N} where N) at C:\Users\enrique.TPNETWORKS\.julia\packages\DocStringExtensions\BEyNH\src\templates.jl:11
 [10] @doc(::LineNumberNode, ::Module, ::String, ::Vararg{Any,N} where N) at .\boot.jl:461
 [11] include at .\boot.jl:328 [inlined]
 [12] include_relative(::Module, ::String) at .\loading.jl:1105
 [13] include at .\Base.jl:31 [inlined]
 [14] include(::String) at C:\Users\enrique.TPNETWORKS\.julia\packages\MCHammer\FkWdn\src\MCHammer.jl:1
 [15] top-level scope at C:\Users\enrique.TPNETWORKS\.julia\packages\MCHammer\FkWdn\src\MCHammer.jl:42
 [16] include at .\boot.jl:328 [inlined]
 [17] include_relative(::Module, ::String) at .\loading.jl:1105
 [18] include(::Module, ::String) at .\Base.jl:31
 [19] top-level scope at none:2
 [20] eval at .\boot.jl:330 [inlined]
 [21] eval(::Expr) at .\client.jl:425
 [22] top-level scope at .\none:3
in expression starting at C:\Users\enrique.TPNETWORKS\.julia\packages\MCHammer\FkWdn\src\mch_charts.jl:153
in expression starting at C:\Users\enrique.TPNETWORKS\.julia\packages\MCHammer\FkWdn\src\mch_charts.jl:55
in expression starting at C:\Users\enrique.TPNETWORKS\.julia\packages\MCHammer\FkWdn\src\mch_charts.jl:55
in expression starting at C:\Users\enrique.TPNETWORKS\.julia\packages\MCHammer\FkWdn\src\MCHammer.jl:42
ERROR: Failed to precompile MCHammer [58716550-704d-11e9-05c2-8f708e47025f] to C:\Users\enrique.TPNETWORKS\.julia\compiled\v1.3\MCHammer\RtvY9_QEBI0.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
```

**Comment by kimikage** [comment]
The last version which supports "deep sky blue" is Colors v0.9.6 for now.
However, I guess there are other problems besides the color parser.

**Comment by etorkia** [comment]
Indeed it does. I have 2 environments deployed... JuliaPro 1.2 and Julia 1.3. The Julia Pro has 0.9.6 as its latest but 0.11 in Julia 1.3. Clearly the 0.11 is broken. 

Sounds like I should revise the compat to include Colors 0.9.6 in the Project.TOML until we get a fix in place. Keep me posted :)

**Comment by timholy** [comment]
xref https://github.com/JuliaGraphics/Colors.jl/issues/386

**Comment by kimikage** [comment]
@etorkia, I have decided not to recommend the color names with spaces (e.g. "deep sky blue"). 
(cf. JuliaGraphics/Colors.jl#386, https://github.com/JuliaGraphics/Colors.jl/pull/390).
As a result, on Colors.jl v0.10.1 and v0.11.1, although a depwarn is displayed, the  color names with spaces are accepted.

Note that this only solves the color parser problem. Other issues are currently unresolved.

**Comment by etorkia** [comment]
@kimikage Thanks for the update! In all fairness I dont disagree about the named colors... Personally I think it may even be preferable to use CSS hex colors as a default. Do CSS HEX colors work out of the box? is there an example of the syntax I can use?

Thanks!!

Eric

**Comment by bjarthur** [comment]
what's the latest with Colors?  should Gadfly add 0.10 and 0.11 as compatible?

**Comment by kimikage** [comment]
The problem of causing segfault in Julia v1.0.x has not been resolved for now. (cf. https://github.com/JuliaLang/julia/issues/34121)
Perhaps it is not a problem with Colors.jl alone. We know a possible workaround, but we also need to be a little careful to use it.

In Colors.jl, we are trying to merge several some PRs with breaking changes. In other words, we have the opportunity to release Colors v0.12.0. I think it is a possible option to include the segfault workaround in v0.12.0. Of course, in order to use it with Gadfly, the dependency packages must support it first.

When will you release new version?

cc @timholy

**Comment by bjarthur** [comment]
there's been [a request to tag a new release](https://github.com/GiovineItalia/Gadfly.jl/issues/1378), so would be good to do so as soon as this Colors issue is resolved.

**Comment by timholy** [comment]
Colors 0.11.2 is out; among other changes it disables precompilation on Julia 1.0.x, so hopefully that will prevent segfaults while also incorporating @kimikage's fix for the OP.

**Comment by kimikage** [comment]
Unfortunately, *perhaps*, FixedPointNumbers.jl or/and ColorTypes.jl also need the workarounds. I'm sorry but I don't have enough time to check this for a couple of days.

**Comment by kimikage** [comment]
cf. https://github.com/GiovineItalia/Gadfly.jl/pull/1377#issuecomment-571809271

**Comment by kimikage** [comment]
@etorkia, the current master supports Colors v0.11 (v0.11.2) now. (https://github.com/GiovineItalia/Gadfly.jl/commit/d0ab673c91bbcc18925573d0bb18b40d75913806)
Does the `UndefVarError` still occur?
